spring.application.name=api-mongo
spring.data.mongodb.database=apj-storefront
server.port=8082

logging.level.org.springframework.web=DEBUG

# Actuator: expose health and info over HTTP
management.endpoints.web.exposure.include=health,info

# Springdoc / Swagger UI
springdoc.swagger-ui.path=/docs