spring.application.name=db
server.port=8083

# Enable debug logging
logging.level.org.springframework.web=DEBUG

# H2 configuration
spring.datasource.url=jdbc:h2:mem:apj-storefront
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true


# Actuator: expose health and info over HTTP
management.endpoints.web.exposure.include=health,info

# Springdoc / Swagger UI
springdoc.swagger-ui.path=/docs